imx93-11x11-lpddr4x-evk: fix build issue
With latest meta-freescale(master) layer, imx93 fails to build with
imx-gst1.0-plugin compilation error:

"../git/plugins/videoconvert/gstimxvideoconvert.c:28:10: fatal error: libdrm/drm_fourcc.h: No such file or directory
" #include <libdrm/drm_fourcc.h>
"          ^~~~~~~~~~~~~~~~~~~~~

Add missing libdrm dependency for imx93.

Pick-to: mickledore
Change-Id: I89dc7ccf0402e7b734cd731e9979c203ea5a6d93
Reviewed-by: Samuli Piippo <samuli.piippo@qt.io>