freescale: fix imx93 boot issue
The additional profiling configuration used in the iMX93 kernel
caused its size grow beyond what u-boot was expecting. This caused
DTS to be loaded on top of it, causing boot failure:

  ERROR: FDT image overlaps OS image (OS=80400000..83020000)

Fixes: QTBUG-130658
Change-Id: I198dc35724f8c786a7ef971229b83ec29c3d4f57
Reviewed-by: Mikko Gronoff <mikko.gronoff@qt.io>
(cherry picked from commit 622758db0b046d7fe34cecf37e4ca2ae167c9d9b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>